version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: pitstop-redis
    volumes:
      - pitstop_redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks: [pitstop-network]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pitstop-backend
    environment:
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY:-change-me}
    depends_on: [redis]
    restart: unless-stopped
    networks: [pitstop-network]

  frontend:
    build:
      context: ./frontend
    container_name: pitstop-frontend
    ports:
      - "3654:80"
    depends_on: [backend]
    restart: unless-stopped
    networks: [pitstop-network]

volumes:
  pitstop_redis_data:

networks:
  pitstop-network:
    driver: bridge
